In [7]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
from copy import copy
from data_and_events import data_and_events


In [8]:
class Interactor(data_and_events):
    def __init__(self, image_name) -> None:
        super().__init__(image_name)

    def get_bbox(self, image_name: str):
        obj = data_and_events(image_name)
        cv2.namedWindow("draw a rectangle")
        cv2.setMouseCallback("draw a rectangle", obj.mouse_callback)
        while True:
            img = obj.get_image()
            cv2.imshow("draw a rectangle", img)
            if obj.keyboard_handler() == -1:
                break
        cv2.destroyAllWindows()
        return obj.getbbox()

    def crayon(self, image_name: str):
        obj2=data_and_events(image_name)
        cv2.namedWindow("Right click to remove and left click to add")
        cv2.setMouseCallback(
            "Right click to remove and left click to add", obj2.line_mouse_callback)
        while True:
            img = obj2.get_image()
            cv2.imshow("Right click to remove and left click to add", img)
            if obj2.keyboard_handler() == -1:
                break
        cv2.destroyAllWindows()
        return obj2.mask



In [9]:
image_name="lantern.jpg"
interaction = Interactor(image_name)
start_point, end_point= interaction.get_bbox(image_name)
# FIRST GRABCUT PASS

#start loop
mask = interaction.crayon(image_name)
#refine acc to mask
#ask user if they wanna continue
#exit loop/continue loop




In [10]:
print(start_point, end_point)
print(mask)

(272, 48) (863, 930)
[[10 10 10 ... 10 10 10]
 [10 10 10 ... 10 10 10]
 [10 10 10 ... 10 10 10]
 ...
 [10 10 10 ... 10 10 10]
 [10 10 10 ... 10 10 10]
 [10 10 10 ... 10 10 10]]
